### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by es02** [ryanwinchester/netsuite-php#58] opened 2019-12-18 02:28 UTC
I've been trying to debug some slowness in my application and discovered something after plugging it in to an APM:

NetSuite\NetSuiteClient::__construct is taking around 33.8 _seconds_ to run.

It looks like it's this line thats the cause:
`$this->client = $client ?: new SoapClient($wsdl, $options);`
More specifically that unless the soapclient options are in the goldilocks zone soapclient creation will be slow as molasses.

Have tried:
`'cache_wsdl' => WSDL_CACHE_BOTH,` (current default)
`'cache_wsdl' => WSDL_CACHE_MEMORY,`
`'cache_wsdl' => WSDL_CACHE_NONE,`

There was briefly a moment when it was quick, then it went super slow again

**Comment by jrebs** [comment] 2020-01-13 20:52
Sorry for the late reply, @es02 . After the holidays we had a family emergency that has occupied my free time and focus for a while now.

I haven't observed the problem that you're reporting, but the line that you cite is pretty straight forward, assigning a client if one was already present or else instantiating one. Are you suggesting that this is a problem for some reason? If the issue was related to having the right options set, that should be something that the user can define in their environment as needed.

I just did a handful of tests against a prod system  and the total execution time of the commands (which includes db lookups on my end and then remote queries to NS to pull data) are ranging from 0.8 to 2.4 seconds at the upper and lower extremes.

**Comment by jrebs** [comment] 2020-04-01 22:16
Closing this task as I'm not able to reproduce it and no followup with more info. Also the "briefly a moment when it was quick, then went super slow again" suggests something outside the toolkit is interfering.

**Closed by jrebs** 2020-04-01 22:16 UTC

**Comment by ezequiel9** [comment] 2021-02-04 11:26
Hey @jrebs how are you? Question, Is it normal that every request takes around 30 seconds in return something?

**Comment by jrebs** [comment] 2021-02-04 16:27
No, that's not normal. Looking at my web services logs so far this morning my create customer/create order requests are taking about 0.3-0.4 average. The occasional outlier can take almost a full second, but the vast majority of requests are responding in under half a second.
